export default {
	CREATE_USER:'create user',
	SAVE_USER:'save user',
	SAVE_USERNAME:'save username',
	REMOVE_USER:'remove user',
	SAVE_PAGE:'save page',
	SAVE_PREV_PAGE:'save previous page',
	RESTORE:'restore state',
	SAVE_STYLE:'save style',
	SAVE_BLOGS:'save blogs',
	SAVE_BLOG_SEARCH_TERM:'save blog search term',
	SAVE_PEOPLE:'save people',
	EVENT_HAS_IMAGE:'event has image',
	EVENT_IMAGE:'event image',
	BLOG_HAS_IMAGE:'blog has image',
	BLOG_IMAGE:'blog image',
	BUSINESS_IMAGE:'business image',
	SAVE_KEYWORDS:'save keywords',
	SAVE_KEYWORDS_DATE:'save keywords date',

	HAS_SAVED_BUSINESS_SEARCH:'has saved business search',
	SAVE_BUSINESS_SEARCH_TERM:'save business search',
	SAVE_BUSINESS_SEARCH_VALUES:'save business search values',
	SAVE_SEARCHED_BUSINESS:'save searched business',

	HAS_SAVED_EVENT_SEARCH:'has saved event search',
	SAVE_EVENT_SEARCH_TERM:'save event search',
	SAVE_EVENT_SEARCH_VALUES:'save event search values',
	SAVE_SEARCHED_EVENTS:'save searched events'
};